package windows;

import players.HumanPlayer;
import players.Player;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Bastiaan
 */
public class GamePanel extends javax.swing.JPanel implements Runnable {
    
    public Player p1;
    public Player p2;
    //Game settings
    //ControlsS
    int WALKLEFT = 65;
    int WALKRIGHT = 68;
    int PUNCH = 32;
    int KICK = 13;
    //Difficulty
    int difficulty;
    //Map
    Image img = Toolkit.getDefaultToolkit().createImage(".\\zandmapje.jpg");
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
        p1 = new HumanPlayer();
    }
    
    @Override
    public void paint(Graphics g) {
//        super.paint(g);
        g.drawImage(img, 0, 0, null);
        p1.drawPlayer(g);
        //p2.drawPlayer(g);
    }
    
    /**
     *
     * @param map
     */
    public void setMap(String map) {
        try {
            switch(map) {
                case "City": img = Toolkit.getDefaultToolkit().createImage(".\\stadje.jpg");
                    break;
                case "Boat": img = Toolkit.getDefaultToolkit().createImage(".\\boodt.jpg");
                    break;
                case "Desert": img = Toolkit.getDefaultToolkit().createImage(".\\zandmapje.jpg");
                    break;
            }
            System.out.println(map);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 255, 200));
        setPreferredSize(new java.awt.Dimension(930, 626));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void run() {
        System.out.println("run");
        while(true) {
            this.repaint();
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
